export type InputMode = "username" | "url" | "phone" | "email" | "text" | "invite";

export type Platform = {
  id: string;
  name: string;
  iconSource: "brand" | "custom";
  iconKey: string;
  inputMode: InputMode;
  placeholder: string;
  prefixLabel: string;
  helpText: string;
  buildValue: (input: string) => string;
};

const stripAt = (v: string) => v.trim().replace(/^@+/, "");
const stripSlashes = (v: string) => v.trim().replace(/^\/+|\/+$/g, "");
const digitsOnly = (v: string) => v.replace(/[^\d+]/g, "");

export const PLATFORMS: Platform[] = [
  {
    id: "website",
    name: "Website / Custom URL",
    iconSource: "custom",
    iconKey: "website",
    inputMode: "url",
    placeholder: "yourdomain.com/page",
    prefixLabel: "any URL",
    helpText: "Paste any full link — your site, a landing page, a file, anything.",
    buildValue: (v) => {
      const t = v.trim();
      if (!t) return "";
      return /^https?:\/\//i.test(t) ? t : `https://${t}`;
    },
  },
  {
    id: "instagram",
    name: "Instagram",
    iconSource: "brand",
    iconKey: "instagram",
    inputMode: "username",
    placeholder: "yourhandle",
    prefixLabel: "instagram.com/",
    helpText: "Just the handle — no @ needed.",
    buildValue: (v) => `https://instagram.com/${stripAt(v)}`,
  },
  {
    id: "facebook",
    name: "Facebook",
    iconSource: "brand",
    iconKey: "facebook",
    inputMode: "username",
    placeholder: "yourpage",
    prefixLabel: "facebook.com/",
    helpText: "Your page name or profile ID.",
    buildValue: (v) => `https://facebook.com/${stripSlashes(v)}`,
  },
  {
    id: "x",
    name: "X (Twitter)",
    iconSource: "brand",
    iconKey: "x",
    inputMode: "username",
    placeholder: "yourhandle",
    prefixLabel: "x.com/",
    helpText: "Just the handle — no @ needed.",
    buildValue: (v) => `https://x.com/${stripAt(v)}`,
  },
  {
    id: "tiktok",
    name: "TikTok",
    iconSource: "brand",
    iconKey: "tiktok",
    inputMode: "username",
    placeholder: "yourhandle",
    prefixLabel: "tiktok.com/@",
    helpText: "Just the handle — no @ needed.",
    buildValue: (v) => `https://tiktok.com/@${stripAt(v)}`,
  },
  {
    id: "youtube",
    name: "YouTube",
    iconSource: "brand",
    iconKey: "youtube",
    inputMode: "username",
    placeholder: "channelhandle",
    prefixLabel: "youtube.com/@",
    helpText: "Your channel handle (the one starting with @).",
    buildValue: (v) => `https://youtube.com/@${stripAt(v)}`,
  },
  {
    id: "linkedin",
    name: "LinkedIn",
    iconSource: "custom",
    iconKey: "linkedin",
    inputMode: "username",
    placeholder: "yourname",
    prefixLabel: "linkedin.com/in/",
    helpText: "The slug from your profile URL.",
    buildValue: (v) => `https://linkedin.com/in/${stripSlashes(v)}`,
  },
  {
    id: "whatsapp",
    name: "WhatsApp",
    iconSource: "brand",
    iconKey: "whatsapp",
    inputMode: "phone",
    placeholder: "+8801XXXXXXXXX",
    prefixLabel: "wa.me/",
    helpText: "Full number with country code, digits only.",
    buildValue: (v) => `https://wa.me/${digitsOnly(v).replace(/^\+/, "")}`,
  },
  {
    id: "telegram",
    name: "Telegram",
    iconSource: "brand",
    iconKey: "telegram",
    inputMode: "username",
    placeholder: "yourhandle",
    prefixLabel: "t.me/",
    helpText: "Just the handle — no @ needed.",
    buildValue: (v) => `https://t.me/${stripAt(v)}`,
  },
  {
    id: "pinterest",
    name: "Pinterest",
    iconSource: "brand",
    iconKey: "pinterest",
    inputMode: "username",
    placeholder: "yourhandle",
    prefixLabel: "pinterest.com/",
    helpText: "Just the handle.",
    buildValue: (v) => `https://pinterest.com/${stripAt(v)}`,
  },
  {
    id: "snapchat",
    name: "Snapchat",
    iconSource: "brand",
    iconKey: "snapchat",
    inputMode: "username",
    placeholder: "yourhandle",
    prefixLabel: "snapchat.com/add/",
    helpText: "Just the handle.",
    buildValue: (v) => `https://snapchat.com/add/${stripAt(v)}`,
  },
  {
    id: "discord",
    name: "Discord",
    iconSource: "brand",
    iconKey: "discord",
    inputMode: "invite",
    placeholder: "invitecode",
    prefixLabel: "discord.gg/",
    helpText: "The invite code from your server invite link.",
    buildValue: (v) => `https://discord.gg/${stripSlashes(v)}`,
  },
  {
    id: "reddit",
    name: "Reddit",
    iconSource: "brand",
    iconKey: "reddit",
    inputMode: "username",
    placeholder: "yourhandle",
    prefixLabel: "reddit.com/user/",
    helpText: "Just the username.",
    buildValue: (v) => `https://reddit.com/user/${stripAt(v)}`,
  },
  {
    id: "github",
    name: "GitHub",
    iconSource: "brand",
    iconKey: "github",
    inputMode: "username",
    placeholder: "yourhandle",
    prefixLabel: "github.com/",
    helpText: "Just the username.",
    buildValue: (v) => `https://github.com/${stripAt(v)}`,
  },
  {
    id: "spotify",
    name: "Spotify",
    iconSource: "brand",
    iconKey: "spotify",
    inputMode: "username",
    placeholder: "user-id or artist-id",
    prefixLabel: "open.spotify.com/user/",
    helpText: "The ID from your profile/artist share link.",
    buildValue: (v) => `https://open.spotify.com/user/${stripSlashes(v)}`,
  },
  {
    id: "twitch",
    name: "Twitch",
    iconSource: "brand",
    iconKey: "twitch",
    inputMode: "username",
    placeholder: "yourhandle",
    prefixLabel: "twitch.tv/",
    helpText: "Just the channel name.",
    buildValue: (v) => `https://twitch.tv/${stripAt(v)}`,
  },
  {
    id: "threads",
    name: "Threads",
    iconSource: "brand",
    iconKey: "threads",
    inputMode: "username",
    placeholder: "yourhandle",
    prefixLabel: "threads.net/@",
    helpText: "Just the handle — no @ needed.",
    buildValue: (v) => `https://threads.net/@${stripAt(v)}`,
  },
  {
    id: "messenger",
    name: "Messenger",
    iconSource: "brand",
    iconKey: "messenger",
    inputMode: "username",
    placeholder: "yourhandle",
    prefixLabel: "m.me/",
    helpText: "Your Messenger username.",
    buildValue: (v) => `https://m.me/${stripAt(v)}`,
  },
  {
    id: "line",
    name: "LINE",
    iconSource: "brand",
    iconKey: "line",
    inputMode: "username",
    placeholder: "yourid",
    prefixLabel: "line.me/ti/p/~",
    helpText: "Your LINE ID.",
    buildValue: (v) => `https://line.me/ti/p/~${stripAt(v)}`,
  },
  {
    id: "behance",
    name: "Behance",
    iconSource: "brand",
    iconKey: "behance",
    inputMode: "username",
    placeholder: "yourhandle",
    prefixLabel: "behance.net/",
    helpText: "Just the username.",
    buildValue: (v) => `https://behance.net/${stripAt(v)}`,
  },
  {
    id: "dribbble",
    name: "Dribbble",
    iconSource: "brand",
    iconKey: "dribbble",
    inputMode: "username",
    placeholder: "yourhandle",
    prefixLabel: "dribbble.com/",
    helpText: "Just the username.",
    buildValue: (v) => `https://dribbble.com/${stripAt(v)}`,
  },
  {
    id: "medium",
    name: "Medium",
    iconSource: "brand",
    iconKey: "medium",
    inputMode: "username",
    placeholder: "yourhandle",
    prefixLabel: "medium.com/@",
    helpText: "Just the handle — no @ needed.",
    buildValue: (v) => `https://medium.com/@${stripAt(v)}`,
  },
  {
    id: "wechat",
    name: "WeChat",
    iconSource: "brand",
    iconKey: "wechat",
    inputMode: "text",
    placeholder: "yourWeChatID",
    prefixLabel: "WeChat ID",
    helpText: "WeChat has no public profile links, so the code stores your ID as text — the other person scans it, then searches that ID inside WeChat.",
    buildValue: (v) => v.trim(),
  },
  {
    id: "email",
    name: "Email",
    iconSource: "custom",
    iconKey: "email",
    inputMode: "email",
    placeholder: "you@domain.com",
    prefixLabel: "mailto:",
    helpText: "Opens a pre-addressed email when scanned.",
    buildValue: (v) => `mailto:${v.trim()}`,
  },
  {
    id: "phone",
    name: "Phone",
    iconSource: "custom",
    iconKey: "phone",
    inputMode: "phone",
    placeholder: "+8801XXXXXXXXX",
    prefixLabel: "tel:",
    helpText: "Opens the dialer with this number when scanned.",
    buildValue: (v) => `tel:${digitsOnly(v)}`,
  },
];

export const getPlatform = (id: string) => PLATFORMS.find((p) => p.id === id) ?? PLATFORMS[0];
